# Generated by Django 3.1.6 on 2021-02-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('materials', '0002_auto_20210220_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='materials.product'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
