# Generated by Django 3.1.6 on 2021-02-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20210220_2224'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(through='materials.UserProduct', to='materials.Product'),
        ),
    ]
