# Generated by Django 3.1.6 on 2021-02-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20210220_2330'),
        ('user', '0002_profile_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(related_name='products', through='materials.UserProduct', to='materials.Product'),
        ),
    ]
