# Generated by Django 3.1.6 on 2021-02-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210220_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='recyled',
            new_name='recycled',
        ),
    ]
